
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST http://localhost:3333/accounts
Content-Type: application/json

{
    "name": "Romeu777 soarea de souto",
    "email": "romeu777@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "romeu@gmail.com",
    "password": "123456"
}

###

# @name create_question
POST http://localhost:3333/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Outra pergunta",
    "content": "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions
GET http://localhost:3333/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}