version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: bitnamipostgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apiNest
      PGDATA: /data/postgres
    volumes:
      - /data/pg:/data/postgres